services:
  mc:
    image: itzg/minecraft-server:java21
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    environment:
      EULA: true
      MAX_MEMORY: 6G
      USE_AIKAR_FLAGS: true
      ONLINE_MODE: false
      MOTD: "\u00a74\u00a7l\u00a7kyy\u00a74\u00a7l\u0412\u043e\u043d\u043e \u043d\u0430\u0440\u043e\u0434\u0438\u043b\u043e\u0441\u044f\u00a74\u00a7l\u00a7kyy"
      ENABLE_WHITELIST: true
      ENFORCE_SECURE_PROFILE: false
      FUNCTION_PERMISSION_LEVEL: 3
      DIFFICULTY: hard
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /modpack.mrpack
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./modpack.mrpack:/modpack.mrpack
